name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components (API 34)
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build with Gradle (no wrapper)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
          build-root-directory: apk/android-client
          arguments: >-
            assembleDebug assembleRelease --stacktrace --info --warning-mode all --no-daemon

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: apk/android-client/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: apk/android-client/app/build/outputs/apk/release/app-release.apk